server:
  port: 8001

db:
  host: 'localhost'
  username: 'root'
  password: 'Yolo19960@'
  type: 'mysql'
  port: 3306
  database: 'uleam_apu_db'

jwt:
  secret: 'topSecret51'
  expiresIn: 36000

mail:
  mailAccount: 'no-reply@aputransparencia.com'
  mailAccountPassword: 'UsXnqR8wIU7C'
